### ISSUE TITLE
Compiling Issue: haxe.ui.core.Component has no field _allowDispose

### ISSUE THREAD

**Issue by LeonGamerPS1** [Sword352/FnF-Eternal#7]
I have tried compiling on windows and it said this

> D:/FnF-Eternal/.haxelib/haxeui-flixel/git/haxe/ui/backend/ScreenImpl.hx:223: characters 40-53 : haxe.ui.core.Component has no field _allowDispose

**Comment by moxie-coder** [comment]
please don’t put your compiling issue in the title like that, but also did you run the setup?

**Comment by Sword352** [comment]
Use git versions of HaxeUI:
```
haxelib git haxeui-core https://github.com/haxeui/haxeui-core
haxelib git haxeui-flixel https://github.com/haxeui/haxeui-flixel
```
If it asks you about installing haxelib versions, just ignore or type `n`.

**Comment by LeonGamerPS1** [comment]
yeah it still  says the same thing

**Comment by LeonGamerPS1** [comment]
idk what i did wrong here..

**Comment by LeonGamerPS1** [comment]
and i did run setup.bat

**Comment by Sword352** [comment]
try running these:
```
haxelib set haxeui-core git
haxelib set haxeui-flixel git
```

**Comment by LeonGamerPS1** [comment]
thanks, it worked bro

**Comment by moxie-coder** [comment]
np
